/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Manrope',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
        ],
      },
      // Semantic tokens only — values live in src/index.css (:root / :root.dark).
      // Do not add raw palette colours here or in components.
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        'surface-muted': 'var(--color-surface-muted)',
        overlay: 'var(--color-overlay)',
        paper: 'var(--color-paper)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        'text-faint': 'var(--color-text-faint)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'on-solid': 'var(--color-on-solid)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-solid': 'var(--color-primary-solid)',
        'primary-solid-hover': 'var(--color-primary-solid-hover)',
        link: 'var(--color-link)',
        'neutral-solid': 'var(--color-neutral-solid)',
        'neutral-solid-hover': 'var(--color-neutral-solid-hover)',
        danger: {
          DEFAULT: 'var(--color-danger)',
          text: 'var(--color-danger-text)',
          bg: 'var(--color-danger-bg)',
          'bg-strong': 'var(--color-danger-bg-strong)',
          border: 'var(--color-danger-border)',
          solid: 'var(--color-danger-solid)',
          'solid-hover': 'var(--color-danger-solid-hover)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          text: 'var(--color-success-text)',
          bg: 'var(--color-success-bg)',
          'bg-strong': 'var(--color-success-bg-strong)',
          border: 'var(--color-success-border)',
          solid: 'var(--color-success-solid)',
          'solid-hover': 'var(--color-success-solid-hover)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          text: 'var(--color-info-text)',
          bg: 'var(--color-info-bg)',
          'bg-strong': 'var(--color-info-bg-strong)',
          border: 'var(--color-info-border)',
          solid: 'var(--color-info-solid)',
          'solid-hover': 'var(--color-info-solid-hover)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          text: 'var(--color-warning-text)',
          bg: 'var(--color-warning-bg)',
          'bg-strong': 'var(--color-warning-bg-strong)',
          border: 'var(--color-warning-border)',
          solid: 'var(--color-warning-solid)',
        },
        'status-processing-bg': 'var(--color-status-processing-bg)',
        'status-processing-text': 'var(--color-status-processing-text)',
        'status-pending-bg': 'var(--color-status-pending-bg)',
        'status-pending-text': 'var(--color-status-pending-text)',
        'status-verified-bg': 'var(--color-status-verified-bg)',
        'status-verified-text': 'var(--color-status-verified-text)',
        'status-failed-bg': 'var(--color-status-failed-bg)',
        'status-failed-text': 'var(--color-status-failed-text)',
        'status-mtb-updated-bg': 'var(--color-status-mtb-updated-bg)',
        'status-mtb-updated-text': 'var(--color-status-mtb-updated-text)',
      },
    },
  },
  plugins: [],
};
